services:
  app:
    container_name: jwt_app_v1.0.0
    image: jwt_app:1.0.0
    build:
      context: .
    env_file:
      - ".env.docker"
    ports:
      - 8888:8888
    networks:
      - "app_net"
    depends_on:
      - postgres
    command: "poetry run python ./src/gunicorn/run.py"
    volumes:
      - ./logs:/app/logs

    develop:
      watch:
        - action: rebuild
          path: ./src
          target: /app/src

  postgres:
    container_name: jwt_postgres_db
    image: "postgres:17"
    ports:
      - 6432:5432
    volumes:
      - pg_db_data:/var/lib/postgresql/data
    networks:
      - "app_net"
    env_file:
      - ".env.postgres"
      

volumes:
  pg_db_data:

networks:
  app_net:
    driver: bridge
